// // app/layout.tsx
// import type { Metadata } from 'next';
// import './globals.css';
// import './assets/colors.css';
// import StoreProvider from './StoreProvider';
// import LayoutContent from './LayoutContent';
// import QueryProvider from './QueryProvider';

// export const metadata: Metadata = {
//   title: 'ReelBoost',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <head>
//         <link
//           href="https://fonts.googleapis.com/css?family=Poppins"
//           rel="stylesheet"
//         />
//       </head>
//       <body className="font-poppins">
//         <StoreProvider>
//           <QueryProvider>

//             <LayoutContent>{children}</LayoutContent>
//           </QueryProvider>
//         </StoreProvider>
//       </body>
//     </html>
//   );
// }


import type { Metadata } from 'next';
import './globals.css';
import './assets/colors.css';
import StoreProvider from './StoreProvider';
import LayoutContent from './LayoutContent';

export const metadata: Metadata = {
  title: 'JubJub',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet" />
      </head>
      <body className="font-poppins">
        <StoreProvider>
          <LayoutContent>{children}</LayoutContent>
        </StoreProvider>
      </body>
    </html>
  );
}
